(function(){
'use strict';
const cfg=window.MHUR_COMMUNITY_CONFIG||{};
const API=String(cfg.supabaseUrl||'').replace(/\/+$/,'');
const KEY=String(cfg.supabaseKey||'').trim();
const remote=/^https:\/\/.+\.supabase\.co$/i.test(API)&&!!KEY;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function req(path,opt={}){const token=window.MHUR_AUTH?.getAccessToken?.()||KEY;const r=await fetch(API+path,{...opt,headers:{apikey:KEY,Authorization:`Bearer ${token}`,'Content-Type':'application/json',...(opt.headers||{})}});const t=await r.text();let d=null;try{d=t?JSON.parse(t):null}catch(_){d=t}if(!r.ok)throw new Error(d?.message||d?.hint||t||`HTTP ${r.status}`);return d}
function lastSync(){try{const raw=localStorage.getItem('mhur_last_sync_v322');if(raw)return new Date(raw)}catch(_){}return null}
function statusText(){if(!navigator.onLine)return 'Hors connexion — les données locales restent consultables';if(!remote)return 'Mode local — Supabase doit encore être configuré';const d=lastSync();return d?`En ligne · dernière synchronisation ${d.toLocaleString('fr-FR')}`:'En ligne · communauté connectée'}
function renderStatus(){let bar=document.getElementById('mhurLaunchBar');if(!bar){bar=document.createElement('div');bar.id='mhurLaunchBar';bar.className='mhurLaunchBar';bar.innerHTML='<span class="mhurLaunchDot"></span><span id="mhurLaunchText"></span><button type="button" onclick="MHUR_LAUNCH.refreshStatus()">↻</button>';document.body.appendChild(bar)}bar.classList.toggle('offline',!navigator.onLine);bar.classList.toggle('online',navigator.onLine&&remote);document.getElementById('mhurLaunchText').textContent=statusText()}
function overlay(){let m=document.getElementById('mhurLegalOverlay');if(m)return m;m=document.createElement('div');m.id='mhurLegalOverlay';m.className='mhurLegalOverlay';m.innerHTML='<article class="mhurLegalPanel"><button class="mhurLegalClose" onclick="MHUR_LAUNCH.close()">×</button><div id="mhurLegalBody"></div></article>';m.addEventListener('click',e=>{if(e.target===m)close()});document.body.appendChild(m);return m}
const pages={
privacy:`<h2>Confidentialité</h2><p>Le site utilise Supabase pour les comptes, les builds, les likes, les favoris et la modération. Lors d’une connexion Google ou Discord, nous recevons l’identifiant du compte, le pseudo, l’adresse e-mail et la photo de profil fournis par le service.</p><h3>Données publiques</h3><p>Le pseudo, l’avatar, la date d’inscription et les builds publiés peuvent être visibles par les autres utilisateurs. L’adresse e-mail n’est pas affichée publiquement.</p><h3>Utilisation</h3><p>Les données servent uniquement au fonctionnement de la communauté, à la sécurité, aux favoris, aux statistiques et à la modération.</p><h3>Suppression</h3><p>Un utilisateur connecté peut demander la suppression de son compte ci-dessous. La demande sera visible par l’administrateur.</p><div class="mhurDeleteRequest"><button id="mhurDeleteAccountButton" onclick="MHUR_LAUNCH.requestDeletion()">Demander la suppression de mon compte</button><p id="mhurDeleteAccountMessage"></p></div>`,
rules:`<h2>Règles de la communauté</h2><ol><li>Publie des builds réellement utilisables et décris clairement leur objectif.</li><li>Pas de spam, publicité, harcèlement, insultes ou contenu inapproprié.</li><li>Ne copie pas le pseudo ou l’identité d’un autre utilisateur.</li><li>Les signalements abusifs peuvent être ignorés.</li><li>Les modérateurs peuvent masquer un contenu qui enfreint les règles.</li></ol><h3>Build vérifié</h3><p>Le badge « Vérifié » signifie qu’un modérateur a contrôlé le build. Il ne garantit pas qu’il s’agit du meilleur build possible.</p>`,
about:`<h2>À propos</h2><p>MY HERO ULTRA RUMBLE FRANCE est un projet communautaire indépendant consacré aux personnages, costumes, T.U.N.I.N.G, builds et patch notes.</p><p>Ce site n’est pas affilié, approuvé ou administré par Bandai Namco Entertainment, Byking, Kohei Horikoshi ou les détenteurs des droits de My Hero Academia.</p><p>Les marques, noms et visuels appartiennent à leurs propriétaires respectifs.</p>`
};
function open(type){const m=overlay();document.getElementById('mhurLegalBody').innerHTML=pages[type]||pages.about;m.classList.add('open');document.body.classList.add('cbModalOpen');if(type==='privacy'){const b=document.getElementById('mhurDeleteAccountButton');if(b&&!window.MHUR_AUTH?.getUser?.()){b.disabled=true;document.getElementById('mhurDeleteAccountMessage').textContent='Connecte-toi pour envoyer une demande.'}}}
function close(){overlay().classList.remove('open');if(!document.querySelector('.cbModal.open,.mhurAuthOverlay.open,.mhurPublicProfileModal.open,.mhurModerationOverlay.open'))document.body.classList.remove('cbModalOpen')}
async function requestDeletion(){if(!window.MHUR_AUTH?.requireLogin?.('Connecte-toi pour demander la suppression du compte.'))return;const u=window.MHUR_AUTH.getUser();const b=document.getElementById('mhurDeleteAccountButton'),msg=document.getElementById('mhurDeleteAccountMessage');b.disabled=true;try{if(!remote)throw new Error('Supabase non configuré');await req('/rest/v1/account_deletion_requests',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({user_id:u.id,status:'pending',requested_at:new Date().toISOString()})});msg.textContent='Demande enregistrée. Un administrateur pourra la traiter.'}catch(e){b.disabled=false;msg.textContent='Impossible d’envoyer la demande : '+(e.message||e)}}
function footer(){if(document.getElementById('mhurLegalFooter'))return;const f=document.createElement('footer');f.id='mhurLegalFooter';f.className='mhurLegalFooter';f.innerHTML='<button onclick="MHUR_LAUNCH.open(\'privacy\')">Confidentialité</button><button onclick="MHUR_LAUNCH.open(\'rules\')">Règles</button><button onclick="MHUR_LAUNCH.open(\'about\')">À propos</button><span>Projet communautaire non officiel · Version V326</span>';document.body.appendChild(f)}
window.MHUR_LAUNCH={open,close,requestDeletion,refreshStatus:renderStatus};
document.addEventListener('DOMContentLoaded',()=>{footer();renderStatus()});window.addEventListener('online',renderStatus);window.addEventListener('offline',renderStatus);
})();